# Generated by Django 2.0.5 on 2018-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=66)),
                ('trace_id', models.IntegerField(default=0)),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('block_number', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('value', models.IntegerField()),
                ('other_address', models.CharField(db_index=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('block_number', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('value', models.IntegerField()),
                ('gas_price', models.IntegerField(default=0)),
                ('gas_used', models.IntegerField(default=0)),
                ('function', models.CharField(max_length=10)),
                ('other_address', models.CharField(db_index=True, max_length=42)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='internaltransaction',
            unique_together={('hash', 'trace_id')},
        ),
    ]
