# Generated by Django 2.0.5 on 2018-05-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherscanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransaction',
            name='trace_id',
            field=models.CharField(max_length=66),
        ),
    ]
